In [6]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"C:\Users\Admin\Desktop\customer-trends-data-analysis-SQL-Python-PowerBI-main\customer-trends-data-analysis-SQL-Python-PowerBI-main\customer_shopping_behavior.csv")

In [207]:
df.describe(include = "all")

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [101]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [26]:
#review rating have some null value so using midian we can take higer value and lower value of category and fix the missing values of review rating

In [102]:
df['Review Rating'] = df.groupby("Category")['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [103]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [104]:
df.columns = df.columns.str.lower() 
df.columns = df.columns.str.replace(" ","_")  #lower and remove the gap of the columns

In [105]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [106]:
df.rename(columns = {'purchase_amount_(usd)':'purchase amount'},inplace = True)

In [107]:
df.rename(columns={'Purchase Amount (USD)':'purchase_amount'},inplace = True)

In [108]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [24]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [110]:
#create the columns into 4 age group
labels = ["young Age","adult","middle_age","senior"]
df["age_group"] = pd.qcut(df["age"],q =4,labels = labels)

In [23]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [111]:
df[['age','age_group']]

      age   age_group
0      55  middle_age
1      19   young Age
2      50  middle_age
3      21   young Age
4      45  middle_age
...   ...         ...
3895   40       adult
3896   52  middle_age
3897   46  middle_age
3898   44       adult
3899   52  middle_age

[3900 rows x 2 columns]

In [112]:
#create columns purchase_frequency_days
frequency_mapping = {
                     "Fortnightly":14,
                     "Weekly":7,
                     "Monthly":30,
                     "Quarterly":90,
                     "Bi-Weekly":14,
                     "Annually":365,
                    "Every 3 Months":90
}
df["purchased_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)

In [113]:
df.head(1)

,customer_id,age,gender,item_purchased,category,purchase amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchased_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle_age,14

In [123]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchased_frequency_days'],
      dtype='object')

In [ ]:
df[["discount_applied","promo_code_used"]].head(4)

In [ ]:
#the both columns hold the same value do delate one columns
(df["discount_applied"] == df["promo_code_used"]).all()

In [ ]:
df.drop("promo_code_used",axis =1 ,inplace = True)

In [29]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchased_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle_age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young Age,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle_age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young Age,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle_age,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,middle_age,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,senior,90
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,young Age,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,young Age,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,middle_age,90

In [5]:
!pip install mysql-connector-python sqlalchemy pymysql

Requirement already satisfied: mysql-connector-python in c:\users\admin\anaconda3\lib\site-packages (9.6.0)
Requirement already satisfied: sqlalchemy in c:\users\admin\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: pymysql in c:\users\admin\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [127]:
df.head(5)

,customer_id,age,gender,item_purchased,category,purchase amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchased_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle_age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young Age,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle_age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young Age,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle_age,365

In [14]:
import pandas as pd
from sqlalchemy import create_engine

# connect to your Diwali database
engine = create_engine("mysql+pymysql://root:root@localhost:3306/cust")

# read your CSV file
df = pd.read_csv(r"C:\Users\Admin\Desktop\customer-trends-data-analysis-SQL-Python-PowerBI-main\customer-trends-data-analysis-SQL-Python-PowerBI-main\customer_shopping_behavior.csv")

# store CSV into ONE table (you choose name)
df.to_sql(name="customer", con=engine, if_exists="replace", index=False)
print("success")

success

In [ ]:
#clean columns name;
df.columns = df.columns.str.strip().str.replace(" ","_").str.lower()
#remove wrong dublicate headers rows(if any)
df = df[df.iloc[:,0] != df.columns[0]]   
#rename the columns 
df.rename(columns={"purchase_amount_(usd)" : "purchase_amount"},inplace = True)
# puts the one columns into 4 diffrent parts 
labels = ["young Age","adult","middle_age","senior"]
df["age_group"] = pd.qcut(df["age"],q =4,labels = labels)

In [3]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [12]:
df.rename(columns={"purchase_amount_(usd)" : "purchase_amount"},inplace = True)

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group'],
      dtype='object')

In [21]:
#What is the total revenue generated by male  vs female customers
result  = pd.read_sql("select gender, sum(purchase_amount) as revenue  from customer group by gender",engine)
print(result)

   gender   revenue
0    Male  157890.0
1  Female   75191.0

In [22]:
esult  = pd.read_sql("select gender, sum(purchase_amount) as revenue  from customer group by gender",engine)
print(result)

   gender   revenue
0    Male  157890.0
1  Female   75191.0

In [27]:
labels = ["young Age","adult","middle_age","senior"]
df["age_group"] = pd.qcut(df["age"],q =4,labels = labels)

In [ ]:
labels =labels = ["young Age","adult","middle_age","senior"]
df["age_group"] = pd.qcut(df[age]),q = 4,label =label)

In [24]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group'],
      dtype='object')

In [ ]:
s